/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTriageRouteImport } from './routes/admin/triage'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin/diagnostics'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminSystemDiagnosticsRouteImport } from './routes/admin/system/diagnostics'
import { Route as AdminSettingsOperationsRouteImport } from './routes/admin/settings/operations'
import { Route as AdminSettingsDataRouteImport } from './routes/admin/settings/data'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTriageRoute = AdminTriageRouteImport.update({
  id: '/admin/triage',
  path: '/admin/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/admin/diagnostics',
  path: '/admin/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemDiagnosticsRoute = AdminSystemDiagnosticsRouteImport.update({
  id: '/admin/system/diagnostics',
  path: '/admin/system/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsOperationsRoute = AdminSettingsOperationsRouteImport.update({
  id: '/admin/settings/operations',
  path: '/admin/settings/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsDataRoute = AdminSettingsDataRouteImport.update({
  id: '/admin/settings/data',
  path: '/admin/settings/data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/our-story': typeof OurStoryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/triage': typeof AdminTriageRoute
  '/admin/settings/data': typeof AdminSettingsDataRoute
  '/admin/settings/operations': typeof AdminSettingsOperationsRoute
  '/admin/system/diagnostics': typeof AdminSystemDiagnosticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/our-story': typeof OurStoryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/triage': typeof AdminTriageRoute
  '/admin/settings/data': typeof AdminSettingsDataRoute
  '/admin/settings/operations': typeof AdminSettingsOperationsRoute
  '/admin/system/diagnostics': typeof AdminSystemDiagnosticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/our-story': typeof OurStoryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/triage': typeof AdminTriageRoute
  '/admin/settings/data': typeof AdminSettingsDataRoute
  '/admin/settings/operations': typeof AdminSettingsOperationsRoute
  '/admin/system/diagnostics': typeof AdminSystemDiagnosticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/our-story'
    | '/privacy-policy'
    | '/register'
    | '/resources'
    | '/services'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/diagnostics'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/triage'
    | '/admin/settings/data'
    | '/admin/settings/operations'
    | '/admin/system/diagnostics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/our-story'
    | '/privacy-policy'
    | '/register'
    | '/resources'
    | '/services'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/diagnostics'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/triage'
    | '/admin/settings/data'
    | '/admin/settings/operations'
    | '/admin/system/diagnostics'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/our-story'
    | '/privacy-policy'
    | '/register'
    | '/resources'
    | '/services'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/diagnostics'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/triage'
    | '/admin/settings/data'
    | '/admin/settings/operations'
    | '/admin/system/diagnostics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  OurStoryRoute: typeof OurStoryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminTriageRoute: typeof AdminTriageRoute
  AdminSettingsDataRoute: typeof AdminSettingsDataRoute
  AdminSettingsOperationsRoute: typeof AdminSettingsOperationsRoute
  AdminSystemDiagnosticsRoute: typeof AdminSystemDiagnosticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/triage': {
      id: '/admin/triage'
      path: '/admin/triage'
      fullPath: '/admin/triage'
      preLoaderRoute: typeof AdminTriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/admin/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system/diagnostics': {
      id: '/admin/system/diagnostics'
      path: '/admin/system/diagnostics'
      fullPath: '/admin/system/diagnostics'
      preLoaderRoute: typeof AdminSystemDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/operations': {
      id: '/admin/settings/operations'
      path: '/admin/settings/operations'
      fullPath: '/admin/settings/operations'
      preLoaderRoute: typeof AdminSettingsOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/data': {
      id: '/admin/settings/data'
      path: '/admin/settings/data'
      fullPath: '/admin/settings/data'
      preLoaderRoute: typeof AdminSettingsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  OurStoryRoute: OurStoryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminTriageRoute: AdminTriageRoute,
  AdminSettingsDataRoute: AdminSettingsDataRoute,
  AdminSettingsOperationsRoute: AdminSettingsOperationsRoute,
  AdminSystemDiagnosticsRoute: AdminSystemDiagnosticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
